-- Find what's actually available
#check (· ≤ · : Rat → Rat → Prop)
#check (instLT Rat)
#check (lt_of_lt_of_le (a b c : Rat) : a < b → b ≤ c → a < c)
#check (add_lt_add_right (a b : Rat) (c : Rat) : a < b → a + c < b + c)
#check (mul_lt_mul_of_pos_right : a < b → 0 < c → a * c < b * c)
#check (sub_eq_add_neg (a b : Rat) : a - b = a + -b)
#check (add_comm (a b : Rat) : a + b = b + a)
#check (add_assoc (a b c : Rat) : a + b + c = a + (b + c))
#check (mul_comm (a b : Rat) : a * b = b * a)
#check (mul_assoc (a b c : Rat) : a * b * c = a * (b * c))
#check (add_left_neg (a : Rat) : -a + a = 0)
#check (mul_zero (a : Rat) : a * 0 = 0)
#check (zero_mul (a : Rat) : 0 * a = 0)
#check (mul_one (a : Rat) : a * 1 = a)
#check (one_mul (a : Rat) : 1 * a = a)
